USE [master]
GO
/****** Object:  Database [MAF]    Script Date: 11/8/2022 4:18:43 PM ******/
CREATE DATABASE [MAF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MCAF', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\MCAF.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MCAF_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\MCAF_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [MAF] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MAF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MAF] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MAF] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MAF] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MAF] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MAF] SET ARITHABORT OFF 
GO
ALTER DATABASE [MAF] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MAF] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MAF] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MAF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MAF] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MAF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MAF] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MAF] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MAF] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MAF] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MAF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MAF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MAF] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MAF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MAF] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MAF] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MAF] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MAF] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MAF] SET  MULTI_USER 
GO
ALTER DATABASE [MAF] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MAF] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MAF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MAF] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [MAF] SET DELAYED_DURABILITY = DISABLED 
GO
USE [MAF]
GO
/****** Object:  Table [dbo].[ms_storage_location]    Script Date: 11/8/2022 4:18:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ms_storage_location](
	[location_id] [varchar](10) NOT NULL,
	[location_name] [varchar](100) NULL,
 CONSTRAINT [PK_ms_storage_location] PRIMARY KEY CLUSTERED 
(
	[location_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tr_bpkb]    Script Date: 11/8/2022 4:18:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tr_bpkb](
	[agreement_number] [varchar](100) NOT NULL,
	[bpkb_no] [varchar](100) NULL,
	[branch_id] [varchar](10) NULL,
	[bpkb_date] [datetime] NULL,
	[faktur_no] [varchar](100) NULL,
	[faktur_date] [datetime] NULL,
	[location_id] [varchar](10) NULL,
	[police_no] [varchar](20) NULL,
	[bpkb_date_in] [datetime] NULL,
 CONSTRAINT [PK_tr_bpkb] PRIMARY KEY CLUSTERED 
(
	[agreement_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tr_bpkb]  WITH CHECK ADD  CONSTRAINT [FK_tr_bpkb_ms_storage_location] FOREIGN KEY([location_id])
REFERENCES [dbo].[ms_storage_location] ([location_id])
GO
ALTER TABLE [dbo].[tr_bpkb] CHECK CONSTRAINT [FK_tr_bpkb_ms_storage_location]
GO
USE [master]
GO
ALTER DATABASE [MAF] SET  READ_WRITE 
GO
